# This is a sample database file for the DataMapper ORM
:development: &defaults
  :adapter: mysql
  :host: localhost
  :database: places_merb_development
  :username: root
  :password: 

:test:
  <<: *defaults
  :database: places_merb_test

:production:
  <<: *defaults
  :database: places_merb_production

rake:
  <<: *defaults